### ISSUE TITLE
Error while using relative urls

### ISSUE THREAD

**Issue by deep9** [mondeja/mkdocs-include-markdown-plugin#5]
Hi, I'm getting following error
```
ERROR   -  Error reading page 'quickstart/index.md': relpath() argument must be str or bytes, not 'PosixPath'
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/__main__.py", line 192, in <module>
    cli()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/commands/build.py", line 271, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/commands/build.py", line 168, in _populate_page
    'page_markdown', page.markdown, page=page, config=config, files=files
  File "/usr/local/lib/python3.5/dist-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs_include_markdown_plugin/plugin.py", line 8, in on_page_markdown
    return _on_page_markdown(markdown, page, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs_include_markdown_plugin/event.py", line 107, in _on_page_markdown
    markdown)
  File "/usr/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs_include_markdown_plugin/event.py", line 91, in found_include_markdown_tag
    destination_path=page_src_path,
  File "/usr/local/lib/python3.5/dist-packages/mkdocs_include_markdown_plugin/process.py", line 134, in rewrite_relative_urls
    markdown
  File "/usr/lib/python3.5/re.py", line 182, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs_include_markdown_plugin/process.py", line 124, in found_href
    rewritten_url = rewrite_url(href)
  File "/usr/local/lib/python3.5/dist-packages/mkdocs_include_markdown_plugin/process.py", line 108, in rewrite_url
    destination_path.parent)
  File "/usr/lib/python3.5/posixpath.py", line 460, in relpath
    genericpath._check_arg_types('relpath', path, start)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: relpath() argument must be str or bytes, not 'PosixPath'

```

for this snippet

```
{% 
    include-markdown "../../_snippets/where-to-go-next.md"
    start="<!--intro-start-->"
    end="<!--intro-end-->"
%}
```

With  `rewrite_relative_urls=false`  it works.

Maybe it is related to the snippets not being part of the docs folder

```bash
.
├── README.md
├── dictionary.txt
├── mkdocs.yml
├── src
│   ├── _snippets
│   ├── docs
├── tsconfig.json
└── tslint.json

```
mkdocs.yml

```yml
site_dir: 'build'
docs_dir: 'src/docs'
```

This also brings me to feature request, yould it be possible in the plugin configuration to specify default source folder?

Thanks for looking into this.

**Comment by mondeja** [comment]
Thank you for open this. :+1:

The problem is that you are using Python v3.5, when that version reached his end of life in September of this year. Sorry, this package it's supported from version 3.6 onwards. I'm going to add a flag in setup to display a warrning trying to install in older versions.

**Comment by YannickJadoul** [comment]
@mondeja Seems you released as 2.2.1, instead of 2.1.1? (while the versions in the files are correct, being 2.1.1)

**Comment by mondeja** [comment]
> Seems you released as 2.2.1, instead of 2.1.1? (while the versions in the files are correct, being 2.1.1)

Ups :sweat_smile: Thanks for advising @YannickJadoul

**Comment by YannickJadoul** [comment]
Small and easy mistake ;-)

**Comment by deep9** [comment]
@mondeja Thank you for the quck reply, I did not notice the python version.

But I think I have another issue with relative urls, when using mailto. [contact us](mailto:hello@example.com) is translated to <a href="mailto:../../_snippets/hello@example.com">contact us</a>

**Comment by mondeja** [comment]
Thank you so much for the report :pray:

This has been fixed in new release `2.1.2`. Could you check that everything is OK?

**Comment by mirk8s** [comment]
> This also brings me to feature request, yould it be possible in the plugin configuration to specify default source folder?

This has not been done, correct? 

> {%
>    include-markdown "docs/includes/header.md"
>    heading-offset=1
> %}

Also the example above in the README documentation is not working for me.
Is there a way to provide absolute paths starting with "docs/..."? (only absolute paths of File System are currenltly working for me)

**Comment by mondeja** [comment]
> This has not been done, correct?

That's right, could you open another issue to track it?

**Comment by mirk8s** [comment]
Sure, done. https://github.com/mondeja/mkdocs-include-markdown-plugin/issues/55
